-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 15:23:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_paqueteriaV1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_paqueteriaV1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_paqueteriaV1` DEFAULT CHARACTER SET utf8 ;
USE `sistema_paqueteriaV1` ;

-- -----------------------------------------------------
-- Table `sistema_paqueteriaV1`.`usuario_finales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_paqueteriaV1`.`usuario_finales` (
  `id_usuario_final` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `sexo` VARCHAR(20) NOT NULL,
  `celular` VARCHAR(50) NOT NULL,
  `ubicacion` VARCHAR(90) NOT NULL,
  `creado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario_final`));


-- -----------------------------------------------------
-- Table `sistema_paqueteriaV1`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_paqueteriaV1`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `sexo` VARCHAR(50) NOT NULL,
  `celular` VARCHAR(50) NOT NULL,
  `correo_electronico` VARCHAR(90) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `creado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_paqueteriaV1`.`paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_paqueteriaV1`.`paquete` (
  `id_paquete` VARCHAR(30) NOT NULL,
  `id_usuario_final` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `peso` VARCHAR(30) NOT NULL,
  `cantidad` INT NOT NULL,
  `costo` INT NULL,
  `creado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_paquete`, `id_usuario_final`, `id_cliente`),
  CONSTRAINT `fk_paquetes_usuario_final1`
    FOREIGN KEY (`id_usuario_final`)
    REFERENCES `sistema_paqueteriaV1`.`usuario_finales` (`id_usuario_final`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquetes_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sistema_paqueteriaV1`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE INDEX `fk_paquetes_usuario_final1_idx` ON `sistema_paqueteriaV1`.`paquete` (`id_usuario_final` ASC) VISIBLE;

-- CREATE INDEX `fk_paquetes_clientes1_idx` ON `sistema_paqueteriaV1`.`paquete` (`id_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_paqueteriaV1`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_paqueteriaV1`.`personal` (
  `id_personal` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `sexo` VARCHAR(30) NOT NULL,
  `niveles_estudios` VARCHAR(30) NOT NULL,
  `correo_electronico` VARCHAR(90) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `creado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_paqueteriaV1`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_paqueteriaV1`.`estados` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_paqueteriaV1`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_paqueteriaV1`.`roles` (
  `id_roles` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_paqueteriaV1`.`personal_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_paqueteriaV1`.`personal_roles` (
  `id_personal` INT NOT NULL,
  `id_roles` INT NOT NULL,
  `creado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `actiualizado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_personal`, `id_roles`),
  CONSTRAINT `fk_personal_has_roles_personal1`
    FOREIGN KEY (`id_personal`)
    REFERENCES `sistema_paqueteriaV1`.`personal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_has_roles_roles1`
    FOREIGN KEY (`id_roles`)
    REFERENCES `sistema_paqueteriaV1`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE INDEX `fk_personal_has_roles_roles1_idx` ON `sistema_paqueteriaV1`.`personal_roles` (`id_roles` ASC) VISIBLE;

-- CREATE INDEX `fk_personal_has_roles_personal1_idx` ON `sistema_paqueteriaV1`.`personal_roles` (`id_personal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_paqueteriaV1`.`paquetes_estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_paqueteriaV1`.`paquetes_estados` (
  `paquetes_id_paquetes` VARCHAR(30) NOT NULL,
  `estados_id_estado` INT NOT NULL,
  `personal_id_personal` INT NOT NULL,
  `creado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`paquetes_id_paquetes`, `estados_id_estado`, `personal_id_personal`),
  CONSTRAINT `fk_paquetes_has_estados_paquetes1`
    FOREIGN KEY (`paquetes_id_paquetes`)
    REFERENCES `sistema_paqueteriaV1`.`paquete` (`id_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquetes_has_estados_estados1`
    FOREIGN KEY (`estados_id_estado`)
    REFERENCES `sistema_paqueteriaV1`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquetes_estados_personal1`
    FOREIGN KEY (`personal_id_personal`)
    REFERENCES `sistema_paqueteriaV1`.`personal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE INDEX `fk_paquetes_has_estados_estados1_idx` ON `sistema_paqueteriaV1`.`paquetes_estados` (`estados_id_estado` ASC) VISIBLE;

-- CREATE INDEX `fk_paquetes_has_estados_paquetes1_idx` ON `sistema_paqueteriaV1`.`paquetes_estados` (`paquetes_id_paquetes` ASC) VISIBLE;

-- CREATE INDEX `fk_paquetes_estados_personal1_idx` ON `sistema_paqueteriaV1`.`paquetes_estados` (`personal_id_personal` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
